from config import *
import draw

if __name__ == '__main__':
    figure, axis = draw.init()
    draw.headline(axis, '深度学习基础', x_pos = WIDTH_4K / 4, y_pos=HEIGHT_4K * 2 / 3, font_properties=noto_sans_sc['ExtraBold'], fontsize=LARGE_SIZE + SMALL_SIZE)
    draw.headline(axis, '适合新手入门的人工智能课程', x_pos=WIDTH_4K / 2, y_pos=HEIGHT_4K / 3, font_properties=noto_sans_sc['Medium'], fontsize=LARGE_SIZE)
    draw.text_h_center(axis, '@machine-learning-series', bottom=ULTRA_OFFSET, font_size=MEDIUM_SIZE + TINY_SIZE)
    draw.image_center(axis, 'res/deep_learning/networkx_sample.png', pos_x=WIDTH_4K * 3 / 4, pos_y=HEIGHT_4K * 2 / 3)
    draw.save('00_00_cover.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '1. 为什么要学？')
    draw.text(axis, '2024 年诺贝尔物理学奖授予约翰·J·霍普菲尔德和杰弗里·E·辛顿，', index=0)
    draw.text(axis, '以表彰他们“通过人工神经网络实现机器学习的基础性发现和发明”。', index=1)
    draw.text(axis, '霍普菲尔德创造了一种可以存储和重建信息的结构。', index=3)
    draw.text(axis, '辛顿发明了一种可以独立发现数据属性的方法，这种方法对于目前使用的大型神经网络至关重要。', index=4)
    draw.text(axis, '基于人工神经网络的机器学习目前正在彻底改变科学、工程和日常生活。', index=5)
    draw.image_2_h_center(axis, 'res/deep_learning/artificial_neural_network.webp', 'res/deep_learning/physics_nobel_prize_2024.webp', bottom=LARGE_OFFSET, scale=1.5)
    draw.save('00_01_why_learn_1.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '1. 为什么要学？')
    draw.text(axis, '(1) AlphaGo 掌握了古老的围棋游戏，击败了围棋世界冠军，并开启了人工智能系统的新时代。', index=1)
    draw.text(axis, '(2) AlphaFold 揭示了数百万种复杂的 3D 蛋白质结构，并帮助科学家了解生命分子如何相互作用。', index=3)
    draw.text(axis, '(3) Telsa FSD 自动驾驶系统，旨在实现车辆从起点到目的地的全程自主驾驶。', index=5)
    draw.text(axis, '(4) Github Copilot 全球最广泛采用的人工智能开发工具。', index=7)
    draw.text(axis, '(5) ChatGPT 能够理解并生成自然语言，用于回答问题、提供建议和进行互动交流。', index=9)
    draw.text(axis, '(6) Apple Intelligence 帮助用户轻松书写、表达自我和完成工作。', index=11)
    draw.text(axis, '(7) Midjourney 根据用户的文本描述生成高度创意的艺术作品和视觉图像。', index=13)
    draw.save('00_01_why_learn_2.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '1. 为什么要学？')
    draw.text(axis, '2024 年诺贝尔化学奖一半授予大卫·贝克，以表彰其“计算蛋白质设计”，', index=0)
    draw.text(axis, '另一半则共同授予德米斯·哈萨比斯和约翰·M·江珀，以表彰其“蛋白质结构预测”。', index=1)
    draw.text(axis, '大卫·贝克成功完成了几乎不可能完成的壮举，制造出全新种类的蛋白质。', index=3)
    draw.text(axis, '德米斯·哈萨比斯和约翰·江珀开发了一种人工智能模型 AlphaFold 来解决一个 50 年前的问题：', index=4)
    draw.text(axis, '预测蛋白质的复杂结构。', index=5)
    draw.image_2_h_center(axis, 'res/deep_learning/proteins.webp', 'res/deep_learning/chemistry_nobel_2024.webp', bottom=LARGE_OFFSET, scale=1.5)
    draw.save('00_01_why_learn_3.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '1. 为什么要学？')
    draw.text(axis, 'ChatGPT 是基于 OpenAI 公司开发的 GPT（Generative Pre-trained Transformer）模型。', index=0)
    draw.text(axis, '它通过深度学习技术，尤其是 Transformer 架构，能够生成与人类对话类似的自然语言文本。', index=1)
    draw.text(axis, 'Attention Is All You Need', index=2)
    draw.image_h_center(axis, 'res/deep_learning/transformer_model_architecture.png', bottom=SMALL_OFFSET, rotate=270)
    draw.save('00_01_why_learn_4.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '2. 机器学习系列')
    draw.text(axis, '(1) 计算机：包含 Python 教程，数据结构与算法， 以及编程基础知识。', index=0)
    draw.text(axis, '(2) 数学：基础数学、微积分、线性代数、概率论、统计学等。', index=1)
    draw.text(axis, '(3) 机器学习：从理论到实践，拆解每个过程，熟练使用主流的机器学习库。', index=2)
    draw.text(axis, '(4) 前沿：探索最新的人工智能技术，包括底层原理实现。', index=3)
    draw.text(axis, 'Github 仓库 (https://github.com/artinte/machine-learning-series)', index=4)
    draw.text_h_center(axis, 'deep_learning/01_introduction/draw_molecules.py', bottom=EXTRA_OFFSET, font_size=CONTENT_FONT_SIZE, margin_left=ULTRA_OFFSET)
    draw.image_h_center(axis, 'res/deep_learning/molecules_c6h12.png', bottom=LARGE_OFFSET, scale=1.2)
    draw.save('00_02_machine_learning_series_1.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '2. 机器学习系列')
    draw.text(axis, '(1) 计算机：Python 教程 、计算机科学导论、数据结构与算法、C语言程序设计', index=0)
    draw.text(axis, '(2) 数学：初等数学 、微积分 第 1 卷 、微积分 第 2 卷 、线性代数 、统计学入门', index=1)
    draw.text(axis, '(3) 机器学习：深度学习基础 、PyTorch 详解 、CUDA 编程、机器学习编译器', index=2)
    draw.text(axis, '普林斯顿大学计算机教材 (https://introcs.cs.princeton.edu)', index=4)
    draw.image_n_h_center(axis, ['res/deep_learning/programming_in_python.png', 'res/deep_learning/programming_in_java.png', 'res/deep_learning/computer_science.png', 'res/deep_learning/algorithms.png'], bottom=EXTRA_OFFSET)
    draw.save('00_02_machine_learning_series_2.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '2. 机器学习系列')
    draw.text(axis, 'OpenStax (https://openstax.org/subjects/math) 数学教科书：', index=0)
    draw.text(axis, '(1) Algebra and Trigonometry', index=1)
    draw.text(axis, '(2) Calculus', index=2)
    draw.text(axis, '(3) College Algebra', index=3)
    draw.text(axis, '(4) Precalculus', index=4)
    draw.text(axis, '(5) Statistics', index=5)
    draw.image_2_h_center(axis, 'res/deep_learning/precalculus_2e.png', 'res/deep_learning/calculus_volume_1.png', bottom=MEDIUM_OFFSET + LARGE_OFFSET, scale=0.6, margin_left=ULTRA_OFFSET*2)
    draw.save('00_02_machine_learning_series_3.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '3.《深度学习基础》介绍')
    draw.text(axis, '《深度学习基础》(Fundamentals of Deep Learning) 是机器学习的入门课程，许多教程都是从', index=0)
    draw.text(axis, 'MNIST 数据集开始，对于初学者，特别是数学和编程基础不牢固的读者来说，难度仍然比较大。', index=1)
    draw.text(axis, '(1) 为了充分理解神经网络，比如为什么要引入梯度这些复杂的概念，网络从零维的数字开始讲起，', index=3)
    draw.text(axis, '然后将其拓展到二维的坐标系中，其中的每个过程都能可视化。', index=4)
    draw.text(axis, '(2) 通过介绍 TensorFlow 中张量、自动微分、模型等概念，讲述市场上机器学习主流库的基本要素，', index=6)
    draw.text(axis, '充分理解神经网络的基础概念，从而能够轻易地切换到其它机器学习库中。', index=7)
    draw.text(axis, '(3) 分别使用 TensorFlow, NumPy, PyTorch, JAX 实现 MNIST 数据集的训练，掌握这些机器学习库', index=9)
    draw.text(axis, '的入门知识。最后手写 micrograd 库结尾，为进阶学习做好充分的准备。', index=10)
    draw.save('00_03_deep_learning_introduction_1.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '3.《深度学习基础》介绍')
    draw.text(axis, 'MNIST 手写数据集包含 60000 个训练样本，10000 个测试样本', index=0)
    draw.text(axis, '美国国家标准技术研究所 (National Institute of Standards and Technology)', index=1)
    draw.image_h_center(axis, 'res/deep_learning/mnist_dataset.png', bottom=MEDIUM_OFFSET, scale=1.5)
    draw.save('00_03_deep_learning_introduction_2.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '3.《深度学习基础》介绍')
    draw.text(axis, 'TensorFlow (https://www.tensorflow.org) 是一个端到端的机器学习开源平台。', index=0)
    draw.text(axis, '它拥有一个全面、灵活的 工具、 库和 社区资源生态系统，让研究人员能够推动机器学习的最新发展，', index=1)
    draw.text(axis, '让开发者能够轻松构建和部署由机器学习驱动的应用程序。', index=2)
    draw.image_h_center(axis, 'res/deep_learning/icon_tensorflow.png', bottom=HEIGHT_4K - ULTRA_OFFSET * 3, scale=0.5)
    draw.text(axis, 'Keras (https://keras.io) 是一个多后端深度学习框架，支持 JAX、TensorFlow 和 PyTorch。', index=8)
    draw.text(axis, '轻松构建和训练计算机视觉、自然语言处理、音频处理、时间序列预测、推荐系统等模型。', index=9)
    draw.image_h_center(axis, 'res/deep_learning/keras_logo.png', bottom=LARGE_OFFSET+EXTRA_OFFSET)
    draw.save('00_03_deep_learning_introduction_3.png')

    figure, axis = draw.init()
    draw.title(axis, '前言-课程介绍')
    draw.subtitle(axis, '3.《深度学习基础》介绍')
    draw.text(axis, '课程目标：微型 Autograd 引擎 (https://github.com/karpathy/micrograd)', index=0)
    draw.text(axis, '在动态构建的有向无环图 (Directed Acyclic Graph) 上实现反向传播（反向模式自动微分），', index=1)
    draw.text(axis, '并在其上使用类似 PyTorch 的 API 实现小型神经网络库。', index=2)
    draw.image_h_center(axis, 'res/deep_learning/make_moons.png', bottom=0, scale=1.5)
    draw.save('00_03_deep_learning_introduction_4.png')
